### ISSUE TITLE
dox incoming

### ISSUE THREAD

**Issue by accessmodifier364** [DriftyDev/CLEAN_Kami5-1.8-BUILDABLE_SRC#2]
cat.mmmax

**Comment by ssllllll** [comment]
doors will be broken, same as windows 🚔

**Comment by ssllllll** [comment]
![image](https://user-images.githubusercontent.com/86989232/140848380-cd0da173-aaa4-4818-9f62-8620631518a2.png)

**Comment by ssllllll** [comment]
👮‍♀️

**Comment by ssllllll** [comment]
🚪

**Comment by Gentleman2292** [comment]
> doors will be broken, same as windows 🚔

hes gonna lavacast our houses :trollface:
