### ISSUE TITLE
safe?

### ISSUE THREAD

**Issue by jraffstar** [DriftyDev/CLEAN_Kami5-1.8-BUILDABLE_SRC#6]
I want to make le epic kami5 rename :trollface: and not get le mmmax rat 👀

**Comment by jraffstar** [comment]
:trollface:

**Comment by DriftyDev** [comment]
my version is safe, max not sure tho

**Comment by jraffstar** [comment]
damn ok

**Comment by DriftyDev** [comment]
but my version is a little biy bugged, fixing later

**Comment by jraffstar** [comment]
what are the bugs

**Comment by master7720** [comment]
none

**Comment by DriftyDev** [comment]
already fixed

**Comment by BebSxy** [comment]
DriftySex
