### ISSUE TITLE
500 pizzas with pineapple in your door

### ISSUE THREAD

**Issue by accessmodifier364** [DriftyDev/CLEAN_Kami5-1.8-BUILDABLE_SRC#7]
oshi package is an open source library made for hwid / take hardware info, you can perfectly google it.

And the .so linux file is an hwid system made in Rust, if you read the code in the hwid things, you can see some native methods which works with that native library.

Take this down 😒

**Comment by DriftyDev** [comment]
thanks for clarifying it.
